# Generated by Django 5.1.4 on 2025-11-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_group_title_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
